CheckSaver/Controllers/ChecksController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CheckSaverCore.CheckSaver;
using CheckSaverCore.DataModels;
using CheckSaverCore.DataModels.InputModels;

namespace CheckSaver.Controllers
{
    public class ChecksController : Controller
    {
        CheckUnitOfWork unit = new CheckUnitOfWork(new checkSaverEntities());
        private int pageSize = 12;

        // GET: Checks
        public ActionResult Index(int pageNum = 0)
        {
            var check = unit.GetChecks(pageSize, pageNum);
            ViewData["PageNum"] = pageNum;
            ViewData["PageCount"] = unit.GetChecksCount() / pageSize;


            if (Request.IsAjaxRequest())
            {
                return PartialView("_checks", check);
            }
            else
            {
                return View(check);
            }
        }

        //public ActionResult Update(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    CheckSaver.Checks check = _repository.FindCheckById(id);
        //    //CheckDetailsModel model = new CheckDetailsModel(check);
        //    if (check == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    ///_repository.UpdateCheck(check);

        //    return RedirectToAction("Details", new { id = check.Id });
        //}


        // GET: Checks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = unit.Checks.GetById(id.Value);

            if (check == null)
            {
                return HttpNotFound();
            }

            Dictionary<Neighbour, decimal> dictonary = new Dictionary<Neighbour, decimal>();

            foreach (Purchase purchase in check.Purchases)
            {
                string summary = string.Empty;
                foreach (WhoWillUse VARIABLE in purchase.WhoWillUse)
                {
                    summary += VARIABLE.Neighbours.Name + ",";
                    if (!dictonary.ContainsKey(VARIABLE.Neighbours))
                    {
                        dictonary.Add(VARIABLE.Neighbours, purchase.CostPerPerson);
                    }
                    else
                    {
                        dictonary[VARIABLE.Neighbours] += purchase.CostPerPerson;
                    }
                }

            }

            List<KeyValuePair<Neighbour, decimal>> TotalList = dictonary.ToList();

            ViewBag.Summary = TotalList;
            return View(check);
        }

        // GET: Checks/Create
        public ActionResult Create()
        {
            ViewBag.NeighborId = new SelectList(unit.GetNeighborsList(), "Id", "Name");
            ViewBag.StoreId = new SelectList(unit.GetStoresList(), "Id", "Title");
            ViewBag.Names = unit.GetNeighboursNames();
            ViewBag.Index = 0;

            return View();
        }

        // POST: Checks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CheckInputModel check)
        {
            if (ModelState.IsValid)
            {
                int newCheckId = unit.Checks.Insert(check);
                return RedirectToAction("Details", new { id = newCheckId });
            }

            ViewBag.NeighborId = new SelectList(unit.GetNeighborsList(), "Id", "Name", check.NeighborId);
            ViewBag.StoreId = new SelectList(unit.GetStoresList(), "Id", "Title", check.StoreId);
            ViewBag.Names = unit.GetNeighboursNames();
            ViewBag.Index = 0;

            return View(check);
        }





        // GET: Checks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = unit.Checks.GetById(id.Value);
            if (check == null)
            {
                return HttpNotFound();
            }
            ViewBag.NeighborId = new SelectList(unit.GetNeighborsList(), "Id", "Name", check.NeighbourId);
            ViewBag.StoreId = new SelectList(unit.GetStoresList(), "Id", "Title", check.StoreId);
            ViewBag.Names = unit.GetNeighboursNames();
            ViewBag.Index = 0;

            return View(check);
        }

        //// POST: Checks/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(CheckInputModel check)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _repository.EditCheck(check);
        //        return RedirectToAction("Details", new { id = check.Id });
        //    }

        //    ViewBag.NeighborId = new SelectList(_repository.GetNeighborsList(), "Id", "Name", check.NeighborId);
        //    ViewBag.StoreId = new SelectList(_repository.GetStoresList(), "Id", "Title", check.StoreId);
        //    ViewBag.Names = _repository.GetNeighboursNames();
        //    ViewBag.Index = 0;
        //    Models.Checks c = _repository.FindCheckById(check.Id);
        //    return View(c);
        //}

        // GET: Checks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = unit.Checks.GetById(id.Value);
            if (check == null)
            {
                return HttpNotFound();
            }
            return View(check);
        }

        // POST: Checks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            unit.Checks.Delete(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        _repository.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}

        //public ActionResult FindProducts(string term, int storeId, string fieldId)
        //{
        //    var products = _repository.FindProductsinDb(term);

        //    var responce = new List<Responce>();
        //    foreach (var product in products)
        //    {
        //        int pricesCount = 0;
        //        foreach (var price in product.Price.OrderByDescending(x => x.Date))
        //        {
        //            if (price.StoreId == storeId)
        //            {
        //                responce.Add(new Responce() { fieldId = fieldId, id = price.Id, price = price.Cost, value = product.Title });
        //                pricesCount++;
        //                break;
        //            }
        //        }
        //        if (pricesCount == 0)
        //        {
        //            responce.Add(new Responce() { fieldId = fieldId, value = product.Title });
        //        }
        //    }

        //    return Json(responce, JsonRequestBehavior.AllowGet);
        //}

        //private class Responce
        //{
        //    public int id { get; set; }
        //    public string value { get; set; }
        //    public decimal price { get; set; }
        //    public string fieldId { get; set; }
        //}

        //public ActionResult ProductBox(string index)
        //{
        //    ViewBag.Names = _repository.GetNeighboursNames();
        //    ViewBag.Index = Convert.ToInt32(index);
        //    return PartialView("ProductBox");
        //}

        //public ActionResult EditProductBox(string index)
        //{
        //    ViewBag.Names = _repository.GetNeighboursNames();
        //    ViewBag.Index = Convert.ToInt32(index);
        //    ViewData["number"] = index;
        //    Purchases p = new Purchases()
        //    {
        //        Id = 0,
        //        Products = new Products() { Title = "" },
        //        Count = 0,
        //        Cost = 0
        //    };
        //    return PartialView("EditProductBox", p);
        //}

        //public ActionResult Recalc()
        //{
        //    //_repository.RecalculateSummas();
        //    return RedirectToAction("Index");
        //}
    }
}

CheckSaver/Controllers/FPNamesController.cs
using System.Web.Mvc;

namespace CheckSaver.Controllers
{
    public class FPNamesController : Controller
    {
        //private InvoicesCS db = new InvoicesCS();

        //// GET: FPNames
        //public ActionResult Index()
        //{
        //    return View(db.FPName.ToList());
        //}

        //// GET: FPNames/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    FPName fPName = db.FPName.Find(id);
        //    if (fPName == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(fPName);
        //}

        //// GET: FPNames/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: FPNames/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Name,Id")] FPName fPName)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.FPName.Add(fPName);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(fPName);
        //}

        //// GET: FPNames/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    FPName fPName = db.FPName.Find(id);
        //    if (fPName == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(fPName);
        //}

        //// POST: FPNames/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Name,Id")] FPName fPName)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(fPName).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(fPName);
        //}

        //// GET: FPNames/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    FPName fPName = db.FPName.Find(id);
        //    if (fPName == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(fPName);
        //}

        //// POST: FPNames/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    FPName fPName = db.FPName.Find(id);
        //    db.FPName.Remove(fPName);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

CheckSaver/Views/Shared/_CalcLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <script src="~/Scripts/semantic.min.js"></script>

    <link href="~/Content/css/semantic.min.css" rel="stylesheet" />

        @RenderBody()

CheckSaver/Views/Shared/_ChecksLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@RenderBody()

@section styles{

}

CheckSaver/Views/Shared/_InvoiceLayour.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <link rel="stylesheet" href="~/Content/css/InvoiceStyles.css" />

    @RenderBody()

CheckSaver/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <style>
        

    </style>

    <script src="~/Scripts/jquery-2.1.3.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.3.min.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/AddFieldsScript.js"></script>

</head>
<body>
    <header id="header">@ViewBag.Title</header>

    <div id="right_menu">
        <span id="logo">
            <img src="https://www.google.com/design/spec/static/images/nav_google_logo.svg" alt="Logo">
        </span>
        <ul>
            <li>
                <a href="@Url.Action("Index", "Checks")">
                    <span class="glyphicon glyphicon-piggy-bank"></span>Чеки
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Transactions")">
                    <span class="glyphicon glyphicon-transfer"></span>Транзакции
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Stores")">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Магазины
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Neighbors")">
                    <span class="glyphicon glyphicon-user"></span>Соседи

                </a>
            </li>
            <li>

                <a href="@Url.Action("Index", "ElectricityTarifs")">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Эл. Тарифы
                </a>
            </li>
            <li>

                <a href="@Url.Action("Index", "FPNames")">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Справочник

                </a>
            </li>
            <li>

                <a href="@Url.Action("Index", "GasTarifs")">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Тарифы газ

                </a>
            </li>
            <li>

                <a href="@Url.Action("Index", "Invoices")">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Квитанции
                </a>
            </li>
            <li>

                <a href="@Url.Action("Index", "WaterTarifs")">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Вода тарифы
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Calculator")">
                    <span class="glyphicon glyphicon-calendar"></span>Калькулятор
                </a>
            </li>
            <li>
                <a href="@Url.Action("FileBrowser", "Calculator")">
                    <span class="glyphicon glyphicon-file"></span>Файлы
                </a>
            </li>

        </ul>
        <div id="legal" class="footer"></div>
    </div>
    <div id="content-panel">
        <div id="content">
            <div id="content-body">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")


    @*@Scripts.Render("~/bundles/animations")*@

    @Styles.Render("~/Content/css");
    <link rel="stylesheet" href="~/Content/css/test.css" />
    @RenderSection("styles", false)
    @RenderSection("scripts", false)
</body>
</html>